version: '3.8'
services:
  sass: 
    image: simple-beauty
    build: .
    volumes:
      - .:/docker/app
  jekyll:
    image: simple-beauty_docs
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - .:/docker/app
    ports:
      - "4000:4000"
      - "35729:35729"